// data.ts
import { loadScores } from "./storage";

export interface Score {
  user: string;
  points: number;
  time: string;
}
export const cityCountryPairs: [string, string][] = [
  ["Tirana", "Albania"],
  ["Algiers", "Algeria"],
  ["Buenos Aires", "Argentina"],
  ["Yerevan", "Armenia"],
  ["Vienna", "Austria"],
  ["Baku", "Azerbaijan"],
  ["Manama", "Bahrain"],
  ["Minsk", "Belarus"],
  ["Antwerp", "Belgium"],
  ["Brussels", "Belgium"],
  ["Bruges", "Belgium"],
  ["Liège", "Belgium"],
  ["Sarajevo", "Bosnia"],
  ["Sucre", "Bolivia"],
  ["São Paulo", "Brazil"],
  ["Rio de Janeiro", "Brazil"],
  ["Sofia", "Bulgaria"],
  ["Calgary", "Canada"],
  ["Montreal", "Canada"],
  ["Ottawa", "Canada"],
  ["Toronto", "Canada"],
  ["Vancouver", "Canada"],
  ["Santiago", "Chile"],
  ["Beijing", "China"],
  ["Shanghai", "China"],
  ["Shenzhen", "China"],
  ["Bogotá", "Colombia"],
  ["San José", "Costa Rica"],
  ["Zagreb", "Croatia"],
  ["Nicosia", "Cyprus"],
  ["Prague", "Czech Republic"],
  ["Copenhagen", "Denmark"],
  ["Cairo", "Egypt"],
  ["Tallinn", "Estonia"],
  ["Helsinki", "Finland"],
  ["Paris", "France"],
  ["Marseille", "France"],
  ["Lyon", "France"],
  ["Toulouse", "France"],
  ["Nice", "France"],
  ["Tbilisi", "Georgia"],
  ["Berlin", "Germany"],
  ["Stuttgart", "Germany"],
  ["Hamburg", "Germany"],
  ["Munich", "Germany"],
  ["Frankfurt", "Germany"],
  ["Cologne", "Germany"],
  ["Athens", "Greece"],
  ["Budapest", "Hungary"],
  ["New Delhi", "India"],
  ["Mumbai", "India"],
  ["Bangalore", "India"],
  ["Jakarta", "Indonesia"],
  ["Tehran", "Iran"],
  ["Dublin", "Ireland"],
  ["Rome", "Italy"],
  ["Turin", "Italy"],
  ["Naples", "Italy"],
  ["Palermo", "Italy"],
  ["Bologna", "Italy"],
  ["Florence", "Italy"],
  ["Genoa", "Italy"],
  ["Tokyo", "Japan"],
  ["Osaka", "Japan"],
  ["Kyoto", "Japan"],
  ["Nairobi", "Kenya"],
  ["Riga", "Latvia"],
  ["Beirut", "Lebanon"],
  ["Vilnius", "Lithuania"],
  ["Kuala Lumpur", "Malaysia"],
  ["Chisinau", "Moldova"],
  ["Podgorica", "Montenegro"],
  ["Amsterdam", "Netherlands"],
  ["Rotterdam", "Netherlands"],
  ["Utrecht", "Netherlands"],
  ["Eindhoven", "Netherlands"],
  ["Auckland", "New Zealand"],
  ["Wellington", "New Zealand"],
  ["Christchurch", "New Zealand"],
  ["Lagos", "Nigeria"],
  ["Ibadan", "Nigeria"],
  ["Kano", "Nigeria"],
  ["Port Harcourt", "Nigeria"],
  ["Oslo", "Norway"],
  ["Islamabad", "Pakistan"],
  ["Lima", "Peru"],
  ["Manila", "Philippines"],
  ["Warsaw", "Poland"],
  ["Lisbon", "Portugal"],
  ["Porto", "Portugal"],
  ["Braga", "Portugal"],
  ["Doha", "Qatar"],
  ["Bucharest", "Romania"],
  ["Moscow", "Russia"],
  ["Kigali", "Rwanda"],
  ["Riyadh", "Saudi Arabia"],
  ["Belgrade", "Serbia"],
  ["Singapore", "Singapore"],
  ["Bratislava", "Slovakia"],
  ["Ljubljana", "Slovenia"],
  ["Johannesburg", "South Africa"],
  ["Cape Town", "South Africa"],
  ["Seoul", "South Korea"],
  ["Busan", "South Korea"],
  ["Incheon", "South Korea"],
  ["Madrid", "Spain"],
  ["Barcelona", "Spain"],
  ["Valencia", "Spain"],
  ["Seville", "Spain"],
  ["Zaragoza", "Spain"],
  ["Málaga", "Spain"],
  ["Murcia", "Spain"],
  ["Palma", "Spain"],
  ["Bilbao", "Spain"],
  ["Colombo", "Sri Lanka"],
  ["Stockholm", "Sweden"],
  ["Gothenburg", "Sweden"],
  ["Malmö", "Sweden"],
  ["Bangkok", "Thailand"],
  ["Ankara", "Turkey"],
  ["Kyiv", "Ukraine"],
  ["London", "United Kingdom"],
  ["Birmingham", "United Kingdom"],
  ["Manchester", "United Kingdom"],
  ["Glasgow", "United Kingdom"],
  ["Washington, D.C.", "United States"],
  ["New York City", "United States"],
  ["Los Angeles", "United States"],
  ["Chicago", "United States"],
  ["Abu Dhabi", "United Arab Emirates"],
  ["Dubai", "United Arab Emirates"],
  ["Montevideo", "Uruguay"],
  ["Caracas", "Venezuela"],
  ["Hanoi", "Vietnam"],
];

export const scores: Score[] = loadScores();
